name: build

on:
  - push

env:
  CI: true
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.GH_TOKEN }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  # TODO: If you are not me, you should use your own username and email address.
  GIT_AUTHOR_NAME: '@adamelliotfields'
  GIT_COMMITTER_NAME: '@adamelliotfields'
  GIT_AUTHOR_EMAIL: 'adam.elliot.fields@gmail.com'
  GIT_COMMITTER_EMAIL: 'adam.elliot.fields@gmail.com'

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-

      - name: NPM
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --coverage

      - name: Code Climate
        run: |
          export GIT_COMMIT_SHA="$GITHUB_SHA"
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          sudo wget -qO /usr/local/bin/cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          sudo chmod +x /usr/local/bin/cc-test-reporter
          cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
          cc-test-reporter upload-coverage

      - name: Build
        run: npm run build

      - name: Release
        if: github.ref == 'refs/heads/master'
        run: npm run semantic-release
